name: <%= File.basename(Dir.pwd) %>
windows:
  - docker:
      pre: eval "$(docker-machine env default)"
      panes:
        - docker-compose up
        -
  - ruby:
      panes:
        - bundle exec guard
        - rerun bundle exec rackup
        -
