version: '3'
services:
  web:
    build: .
    image: sinatra-template/web
    environment:
      RACK_ENV: production
      DB: "postgres://db-user:db-password@db/sinatra-template-db"
    depends_on:
      - db
    ports:
      - '80:9292'

  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-password
      POSTGRES_DB: sinatra-template-db

    # TODO Enable this only in development
    ports:
      - '5432:5432'
